name: log2dyno

services:
  log2dyno:
    build: .
    container_name: log2dyno
    restart: unless-stopped
    ports:
      - "3300:3300"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3300
